#!/bin/sh
# 1. Frontend Checks
cd frontend
echo "Running pre-commit TypeScript checks and Unit Tests..."
npm run typecheck && npm run test || exit 1

# 2. Backend Checks
cd ../backend
echo "Running pre-commit Python Pyright checks..."
venv/bin/pyright -p . || exit 1

