#!/bin/sh
# 1. Format Staged Files
cd frontend
echo "Running pre-commit lint-staged (Prettier auto-formatting)..."
npm run lint-staged || exit 1

# 2. Frontend Checks
echo "Running pre-commit Unit Tests..."
npm run test || exit 1

# 3. Backend Checks
cd ../backend
echo "Running pre-commit Python Pyright checks..."
export PYRIGHT_PYTHON_FORCE_SYSTEM_NODE=1
if [ -f "venv/Scripts/pyright.exe" ] || [ -f "venv/Scripts/pyright" ]; then
    venv/Scripts/pyright -p . || exit 1
elif [ -f "venv/bin/pyright" ]; then
    venv/bin/pyright -p . || exit 1
else
    python -m pyright -p . || exit 1
fi

